package:
  name:  scikit-identification
  version: "0.0.0"

source:
  path: .

requirements:
  build:
    - python==3.7.6
    - setuptools==45.1.0
    - numpy==1.17.3
    - pandas==0.25.3
    - scipy==1.3.2
    - osqp==0.6.1
    - numexpr==2.7.1
    - scikit-learn==0.22.1
  run:
    - python==3.7.6
    - numpy==1.17.3
    - pandas==0.25.3
    - scipy==1.3.2
    - osqp==0.6.1
    - numexpr==2.7.1
    - scikit-learn==0.22.1

about:
  description: "Scikit Identificaiton python package created by Giovanni Licitra."
  home: https://github.com/G-Licitra/scikit-identification
  readme: README.md
