package:
  name:  neurofeat
  version: "0.5.1"

source:
  path: .

requirements:
  build:
    - python==3.7.6
    - setuptools==45.1.0
    - numpy==1.17.3
    - pandas==0.25.3
    - scipy==1.3.2
    - osqp==0.6.1
    - numexpr==2.7.1
    - scikit-learn==0.22.1
  run:
    - python==3.7.6
    - numpy==1.17.3
    - pandas==0.25.3
    - scipy==1.3.2
    - osqp==0.6.1
    - numexpr==2.7.1
    - scikit-learn==0.22.1

about:
  description: "Neurocast's official feature engineering python package."
#  home: https://github.com/Neurocast/neurocast-features-core
#  readme: README.md
